### ISSUE TITLE
Automated Inactive Channel Management

### ISSUE THREAD

**Issue by peartobear** [BoltzExchange/channel-bot#1]
There needs to be a consistent method to close the public channels that are inactive so as to increase the routing score of the boltz node. The currently deployed channel management bot already scans and iterates over the channel every --redacted-- seconds. An additional script to monitor the uptime and downtime of each channel and logging it into the database will provide us with adequate information needed to close the channels periodically.

**Comment by armurbalda** [comment]
As discussed, `getchaninfo` gives us the latest update of a channel which let's us judge if a channel is active or not. Let's use this.

Also we can consider using `listchannels hygiene` and `listchannels inactive` from https://github.com/bitromortac/lndmanage
