### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by matthewlilley** [BoltzExchange/channel-bot#5]
Hey, would you be able to put together a quick start and example config so I can give this a whirl? Looks interesting.

**Comment by michael1011** [comment]
Although this project was intended to be only used internally, there is no reason for which I shouldn't write some documentation. I will add a quickstart guide and a sample config :+1:

**Comment by matthewlilley** [comment]
Thanks @michael1011, much appreciated. I'll look forward to it.
